[env:nano_33_iot]
platform = atmelsam
board = nano_33_iot
framework = arduino
monitor_speed = 115200
extra_scripts = pre:tools/generate_web_assets.py
lib_deps =
  arduino-libraries/WiFiNINA @ ^1.8.14
